spring.application.name=server

spring.datasource.url=jdbc:mysql://localhost:3306/quant_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

collector.python-path=C:/QuantMaster/server/agent/venv/Scripts/python.exe
collector.script-path=C:/QuantMaster/server/agent/stock_collector.py
backtest.script-path=C:/QuantMaster/server/agent/backtest_runner.py
collector.enabled=false